INSERT INTO SURVEY(id,start_date,end_date,description) VALUES(1,CURRENT_DATE(),CURRENT_DATE()+30,'Programming language used in 2018');

INSERT INTO QUESTIONS(QUESTION_ID,text) VALUES(1,'Which language do you use for OOP ?');

INSERT INTO SURVEY_QUESTIONS(survey_id,question_id ) VALUES(1,1);

INSERT INTO  ANSWER(QUESTION_ID,ANSWER_ID,ANSWER_TEXT) VALUES(1,1,'JAVA'); 
INSERT INTO  ANSWER(QUESTION_ID,ANSWER_ID,ANSWER_TEXT) VALUES(1,2,'C#'); 
INSERT INTO  ANSWER(QUESTION_ID,ANSWER_ID,ANSWER_TEXT) VALUES(1,3,'Python'); 
INSERT INTO  ANSWER(QUESTION_ID,ANSWER_ID,ANSWER_TEXT) VALUES(1,4,'Scala'); 

/*INSERT INTO QUESTION_ANSWER(QUESTION_ID,ANSWER_ID) VALUES(1,1);
INSERT INTO QUESTION_ANSWER(QUESTION_ID,ANSWER_ID) VALUES(1,2);
INSERT INTO QUESTION_ANSWER(QUESTION_ID,ANSWER_ID) VALUES(1,3);
INSERT INTO QUESTION_ANSWER(QUESTION_ID,ANSWER_ID) VALUES(1,4);*/


INSERT INTO RESPONSE(RESPONSE_ID,SURVEY_ID,QUESTION_ID,USER_ID,ANSWER_ID) VALUES(1,1,1,1,1);
INSERT INTO RESPONSE(RESPONSE_ID,SURVEY_ID,QUESTION_ID,USER_ID,ANSWER_ID) VALUES(2,1,1,2,2);
INSERT INTO RESPONSE(RESPONSE_ID,SURVEY_ID,QUESTION_ID,USER_ID,ANSWER_ID) VALUES(3,1,1,3,3);
INSERT INTO RESPONSE(RESPONSE_ID,SURVEY_ID,QUESTION_ID,USER_ID,ANSWER_ID) VALUES(4,1,1,4,1);
INSERT INTO RESPONSE(RESPONSE_ID,SURVEY_ID,QUESTION_ID,USER_ID,ANSWER_ID) VALUES(5,1,1,5,2);
INSERT INTO RESPONSE(RESPONSE_ID,SURVEY_ID,QUESTION_ID,USER_ID,ANSWER_ID) VALUES(6,1,1,6,4);